version: 0.1

phases:
  install:
    commands:
      - printenv
      - rm -rf node_modules
      - npm install
  build:
    commands:
      - npm run build -prod
  post_build:
    commands:
      - aws --region us-east-2 s3 sync ./dist/ s3://mys3webpage-1/ --acl=public-read --delete
